
import { Language } from './types';

export const translations: Record<Language, Record<string, string>> = {
    [Language.ENGLISH]: {
        'appTitle': 'EcoLogic',
        'welcome': 'Welcome to EcoLogic',
        'selectRole': 'Please select your role',
        'student': 'Student',
        'teacher': 'Teacher',
        'getStarted': 'Get Started',
        'terms': 'I agree to the Terms & Conditions',
        'factOfTheDay': 'Fact of the Day',
        'leaderboard': 'Leaderboard',
        'streak': 'Streak',
        'ecoPoints': 'Eco Points',
        'myGarden': 'My Garden',
        'classGarden': 'Class Garden',
        'schoolGarden': 'School Garden',
        'challenges': 'Challenges',
        'quizzes': 'Quizzes',
        'shop': 'Shop',
        'journaling': 'Journaling',
        'groupDiscussion': 'Group Discussion',
        'personalGoals': 'Personal Goals',
        'petRescue': 'Pet Rescue',
        'lessons': 'Lessons',
        'impactCalculator': 'Impact Calculator',
        'badges': 'Badges',
        'habitHeatmap': 'Habit Heatmap',
        'spinWheel': 'Spin Wheel',
        'specialEvents': 'Special Events',
        'dashboard': 'Dashboard',
        'analytics': 'Analytics',
        'manageContent': 'Manage Content',
        'verifySubmissions': 'Verify Submissions',
        'assignRoles': 'Assign Roles',
        'studentActivity': 'Student Activity',
        'classActivity': 'Class Activity',
        'createChallenge': 'Create Challenge',
        'createQuiz': 'Create Quiz',
        'uploadLesson': 'Upload Lesson',
    },
    [Language.HINDI]: {
        'appTitle': 'इकोलॉजिक',
        'welcome': 'इकोलॉजिक में आपका स्वागत है',
        'selectRole': 'कृपया अपनी भूमिका चुनें',
        'student': 'विद्यार्थी',
        'teacher': 'शिक्षक',
        'getStarted': 'शुरू करें',
        'terms': 'मैं नियम और शर्तों से सहमत हूं',
        'factOfTheDay': 'आज का तथ्य',
        'leaderboard': 'लीडरबोर्ड',
        'streak': 'स्ट्रीक',
        'ecoPoints': 'इको पॉइंट्स',
        'myGarden': 'मेरा बगीचा',
        'classGarden': 'कक्षा का बगीचा',
        'schoolGarden': 'स्कूल का बगीचा',
        'challenges': 'चुनौतियां',
        'quizzes': 'प्रश्नोत्तरी',
        'shop': 'दुकान',
        'journaling': 'जर्नलिंग',
        'groupDiscussion': 'समूह चर्चा',
        'personalGoals': 'व्यक्तिगत लक्ष्य',
        'petRescue': 'पालतू बचाव',
        'lessons': 'पाठ',
        'impactCalculator': 'प्रभाव कैलकुलेटर',
        'badges': 'बैज',
        'habitHeatmap': 'आदत हीटमैप',
        'spinWheel': 'स्पिन व्हील',
        'specialEvents': 'विशेष आयोजन',
        'dashboard': 'डैशबोर्ड',
        'analytics': 'विश्लेषिकी',
        'manageContent': 'सामग्री प्रबंधित करें',
        'verifySubmissions': 'प्रस्तुतियाँ सत्यापित करें',
        'assignRoles': 'भूमिकाएँ सौंपें',
        'studentActivity': 'छात्र गतिविधि',
        'classActivity': 'कक्षा गतिविधि',
        'createChallenge': 'चुनौती बनाएं',
        'createQuiz': 'प्रश्नोत्तरी बनाएं',
        'uploadLesson': 'पाठ अपलोड करें',
    },
    [Language.BENGALI]: { // Placeholder
        'appTitle': 'ইকোলজিক',
        'welcome': 'ইকোলজিকে স্বাগতম',
        'selectRole': 'আপনার ভূমিকা নির্বাচন করুন',
        'student': 'ছাত্র',
        'teacher': 'শিক্ষক',
        'getStarted': 'শুরু করুন',
    },
    [Language.TELUGU]: { // Placeholder
        'appTitle': 'ఎకోలాజిక్',
        'welcome': 'ఎకోలాజిక్‌కు స్వాగతం',
        'selectRole': 'దయచేసి మీ పాత్రను ఎంచుకోండి',
        'student': 'విద్యార్థి',
        'teacher': 'ఉపాధ్యాయుడు',
        'getStarted': 'ప్రారంభించండి',
    }
};
